CREATE DATABASE sql_project;
USE sql_project;

-- 1. Supplier Table
CREATE TABLE IF NOT EXISTS suppliers (
    sup_id INT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT);

-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    cat_id INT PRIMARY KEY,
    cat_name VARCHAR(255));


-- 3. Employees Table
CREATE TABLE IF NOT EXISTS employees (
    emp_id INT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255));
    
    
-- 4. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    cust_id INT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT);


-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
    prod_id INT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id INT,
    cat_id INT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES suppliers(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 6. Orders Table
CREATE TABLE IF NOT EXISTS orders (
    ord_id INT PRIMARY KEY,
    cust_id INT,
    emp_id INT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id INT,
    prod_id INT,
    quantity INT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

SELECT * FROM suppliers;
SELECT * FROM categories;
SELECT * FROM employees;
SELECT * FROM customers;
SELECT * FROM products;
SELECT * FROM orders;
SELECT * FROM order_details;

-- Analysis Questions
-- 1️. Customer Insights
-- Gain an understanding of customer engagement and purchasing behavior.

-- 1.How many unique customers have placed orders?
select count(distinct(cust_id)) as unique_cust
from orders;

-- 2.Which customers have placed the highest number of orders?
select c.cust_id,c.cust_name, count(o.ord_id) as total_orders from customers c
inner join orders o
on c.cust_id=o.cust_id
group by cust_id
order by total_orders desc
limit 1;
 
-- 3.What is the total and average purchase value per customer?
select c.cust_id , c.cust_name, count(o.ord_id), sum(od.total_price) as total_purchase_value, avg(od.total_price) as avg_purchase_value from customers c
inner join orders o 
on o.cust_id=c.cust_id 
inner join order_details as od
on od.ord_id = o.ord_id
group by c.cust_id
order by c.cust_id asc;

-- 4.Who are the top 5 customers by total purchase amount?
select c.cust_id,c.cust_name, sum(od.total_price) as total_purchase_amount from customers c
join orders o on o.cust_id=c.cust_id
join order_details od on od.ord_id = o.ord_id
group by c.cust_id,c.cust_name
order by total_purchase_amount desc
limit 5;

-- 2. Product Performance
-- Evaluate how well products are performing in terms of sales and revenue.
-- 1.How many products exist in each category?
select c.cat_name, count(prod_id) as products from products p
inner join categories c on c.cat_id=p.cat_id
group by c.cat_name;

-- 2.What is the average price of products by category?
select c.cat_name, avg(od.total_price) as avg_price from products p
inner join categories c on c.cat_id=p.cat_id
inner join order_details od on od.prod_id=p.prod_id
group by c.cat_name;

-- 3.Which products have the highest total sales volume (by quantity)?
select prod_name,sum(od.quantity) as total_quantity_sold from products p
inner join order_details od on od.prod_id=p.prod_id
group by prod_name
order by total_quantity_sold desc;

-- 4.What is the total revenue generated by each product?
select p.prod_name , sum(od.total_price) as total_revenue from products p
inner join order_details od on od.prod_id=p.prod_id
group by p.prod_name;

-- 5.How do product sales vary by category and supplier?
select c.cat_name, s.sup_name , sum(od.quantity) as total_quantity ,sum(od.total_price) as total_revenue from categories c
inner join products p on c.cat_id = p.cat_id
inner join suppliers s on s.sup_id = p.sup_id
inner join order_details od on p.prod_id=od.prod_id
group by c.cat_name, s.sup_name 
order by total_quantity desc;

-- Sales and Order Trends
-- Analyze business performance through orders and revenue over time.
-- 1.How many orders have been placed in total?
select count(ord_id) as total_orders
from orders;

-- 2.What is the average value per order?
select avg(order_total) as average_order_value
from (
    select od.ord_id, sum(od.total_price) as order_total
    from order_details od
    group by od.ord_id
) as order_sums;



-- 3.On which dates were the most orders placed?
select order_date, count(*) as total_orders
from orders
group by order_date
order by total_orders desc
limit 1;


-- 4.What are the monthly trends in order volume and revenue?
select date_format(str_to_date(o.order_date, '%m/%d/%Y'), '%m') as order_month, count(distinct o.ord_id) as total_orders, sum(od.total_price) as total_revenue
from orders o
join order_details od on o.ord_id = od.ord_id
group by order_month
order by order_month;

-- 5.How do order patterns vary across weekdays and weekends?
select 
    case 
        when dayofweek(str_to_date(o.order_date, '%m/%d/%Y')) in (1,7) then 'weekend'
        else 'weekday'
    end as day_type,
    count(distinct o.ord_id) as total_orders,
    sum(od.total_price) as total_revenue
from orders o
join order_details od on o.ord_id = od.ord_id
group by day_type;




-- 4️. Supplier Contribution
-- Identify the most active and profitable suppliers.
-- 1.How many suppliers are there in the database?
select count(sup_id) as no_of_suppliers from suppliers; 

-- 2.Which supplier provides the most products?
select s.sup_id, s.sup_name, count(p.prod_id) as total_products from suppliers s
inner join products p on p.sup_id = s.sup_id
group by s.sup_id , s.sup_name
order by total_products
limit 1;

-- 3.What is the average price of products from each supplier?
select s.sup_name as supplier_name,avg(od.total_price) as average_price
from suppliers s
join products p on s.sup_id = p.sup_id
join order_details od on od.prod_id=p.prod_id
group by s.sup_id, s.sup_name
order by average_price desc;


-- 4.Which suppliers contribute the most to total product sales (by revenue)?
select s.sup_name as supplier_name,sum(od.total_price) as total_revenue
from suppliers s
join products p on s.sup_id = p.sup_id
join order_details od on p.prod_id = od.prod_id
group by s.sup_id, s.sup_name
order by total_revenue desc
limit 1;

-- 5️. Employee Performance
-- Assess how employees are handling and influencing sales.
-- 1.How many employees have processed orders?
select count( distinct emp_id) as total_emp from orders;


-- 2.Which employees have handled the most orders?
select e.emp_id,e.emp_name as employee_name,count(o.ord_id) as total_orders
from employees e
join orders o on e.emp_id = o.emp_id
group by e.emp_id, e.emp_name
order by total_orders desc
limit 1;

-- 3.What is the total sales value processed by each employee?
select e.emp_id,e.emp_name as emp_name,sum(od.total_price) as total_sales_value
from employees e
join orders o on e.emp_id = o.emp_id
join order_details od on o.ord_id = od.ord_id
group by e.emp_id, e.emp_name
order by total_sales_value desc;

-- 4.What is the average order value handled per employee?
select t.emp_id, avg(order_total) as avg_order_value
from (select o.ord_id,o.emp_id,sum(od.total_price) as order_total
    from orders o
    join order_details od on o.ord_id = od.ord_id
    group by o.ord_id, o.emp_id
    ) t
group by t.emp_id;


-- 6️. Order Details Deep Dive
-- Explore item-level sales patterns and pricing behavior.
-- 1.What is the relationship between quantity ordered and total price?
select quantity,avg(total_price) as avg_total_price
from order_details
group by quantity
order by quantity;

-- 2.What is the average quantity ordered per product?
select products.prod_id,products.prod_name, avg(order_details.quantity)  as avg_quantity
from products 
join order_details on products.prod_id= order_details.prod_id group by products.prod_id,products.prod_name;

-- 3.How does the unit price vary across products and orders?
select p.prod_id,p.prod_name,avg(od.each_price) as avg_unit_price
from products p
join order_details od on p.prod_id = od.prod_id
group by p.prod_id, p.prod_name
order by avg_unit_price desc;